### ISSUE TITLE
Typo in "Complexity Waterfall" article

### ISSUE THREAD

**Issue by skatromb** [sobolevn/sobolevn.github.io#86]
In a complexity "Waterfall Article" you write
```python
[
    (x, y, z)
    for x, y, x in itertools.product(x_coords, y_coords, z_coords)
    if valid_coordinates(x, y, z)
]
```

Here is the typo at row with `for` loop:
    for x, y, **x**

Should be:
    x, y, **z**

Here is the link to row with typo:
https://github.com/sobolevn/sobolevn.github.io/blob/master/_posts/2019-10-13-complexity-waterfall.md?plain=1#L159C32-L159C32

**Comment by sobolevn** [comment]
Thanks!
