### ISSUE TITLE
ChatGPT vs Developers.

### ISSUE THREAD

**Issue by whoisoldman** [sobolevn/sobolevn.github.io#93]
Hello! 

First of all, I want to thank you for the video lesson on "str" on the Product Star training platform from RBC. I will express my personal opinion among other teachers of the Python developer course, your lesson differs for the better in the presentation of the material and completeness of thought. The material is easily digested. 

I have a question: what is your opinion on the use of ChatGPT in code creation and what prospects do you see for using Ai in the work of developers, will it replace them? 

Sincerely yours, Mr.OLDMAN.

**Comment by sobolevn** [comment]
Hi! Thanks a lot for your interest in Python :)

> what is your opinion on the use of ChatGPT in code creation and what prospects do you see for using Ai in the work of developers, will it replace them?

AI is out of my area of expertise and out of my zone of interests. So, I don't really pay attention to it. Of course, I've heard a lot of rumors about this topic. But, I only account them as rumors. For me, software development is a hobby, so nothing will change in any case.

The hardest part in software development was always something different, not writting code :)

P.S. Consider taking a look at my new free Python course on YouTube: https://www.youtube.com/@sobolevn

**Comment by whoisoldman** [comment]
Спасибо большое за ответ. Уже подписан на Ваш курс. Слежу за новыми выпусками. Успехов Вам и всего наилучшего.
